### ISSUE TITLE
WRITABLE_PATH /data in Helm chart

### ISSUE THREAD

**Issue by Nightreaver** [wekan/charts#14]
Hello, 

I just figured out that in docker-compose.yaml you are setting a path to store attachments and avatar icons. ( https://github.com/wekan/wekan/blob/master/docker-compose.yml#L149 )
But it seems there no volume/pvc defined in this helm chart, is this an oversight or am I missing something?

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/charts/pull/16
