### ISSUE TITLE
mongodb.architecture standalone not working

### ISSUE THREAD

**Issue by vinzent142** [wekan/charts#19]
Setting mongodb.architecture to standalone provides an `MongoNetworkError: connect ECONNREFUSED`
Reverting to replicaset works fine

I'm pretty new. So ask if more information are needed.

**Comment by xet7** [comment]
@vinzent142 

I think setting is already `replicaset` ?

https://github.com/wekan/charts/blob/main/wekan/values.yaml#L129

**Comment by vinzent142** [comment]
@xet7 
You're right. But changing the value to standalone does not work. 
Maybe out of my scope, so I set `replicaCount` to `1`.

**Comment by xet7** [comment]
@Nightreaver

Does current WeKan Chart still work for you? Or is here some problem?
