### ISSUE TITLE
[Request] Add port value

### ISSUE THREAD

**Issue by markksuite** [wekan/charts#27]
Add port value, or use service.port (8080 by default)

Use this value in deployment.yaml, to ports and livenessProbe/readinessProbe sections

**Comment by markksuite** [comment]
Ex. 
...
containerPort: {{ .Values.service.port }}
...

**Comment by xet7** [comment]
@markksuite

Please send PR. Thanks!

**Comment by markksuite** [comment]
#28

**Comment by markksuite** [comment]
Thanks for merging

**Comment by xet7** [comment]
https://github.com/wekan/charts/pull/28
