### ISSUE TITLE
Better documentation for mongodb persistence

### ISSUE THREAD

**Issue by emoritzx** [wekan/charts#34]
`values.yml` suggests that you can use an existing PVC by setting `mongodb.persistence.existingClaim`, but that claim will not actually be used unless you also set `mongodb.architecture: standalone` and `mongodb.useStatefulSet: false`.

**Comment by emoritzx** [comment]
Also required to manually set `MONGO_URL` in the wekan Deployment as the chart still sets the URL as if it is a replicaset

**Comment by xet7** [comment]
@emoritzx 

Can you send PR that has all of those changes?
