### ISSUE TITLE
Chart v1.1.1 disappeared

### ISSUE THREAD

**Issue by mrtndwrd** [wekan/charts#5]
Since 09972885ef4cf0ed033da621361c37f05c006799 it seems like chart version 1.1.1 (added in 6184a1b9ad39daefd148df811d7ac08a751e0d95) is not available anymore. It also seems like that commit changed the app version metadata without changing anything about the actual chart(s) provided (except removind 1.1.1). However, it seems like the chart that is in the wekan/wekan repository *is* updated. 

The Wekan chart situation is a bit confusing too. There is a helm chart in this repository. https://wekan.github.io/charts/ points to this repository too. But it seems like the chart that is used (and possibly even the chart that is served in this repo's gh-pages branch) is the one from wekan/wekan.

If my hunches are correct, this is what I think would be a solution for the confusion as well as the currently missing chart(s):

1. Remove the `wekan` folder from this repository
2. Follow the "publish chart" readme @varac wrote for future chart versions (https://github.com/wekan/charts/blob/gh-pages/README.publish-chart.md) -- including the chart version upgrade in wekan/wekan and the `helm package` and `helm repo index` commands in this repository (note that the `README.publis-chart.md` doesn't mention the  `git add` and `git commit` commands necessary to actually make the charts reachable.

**Comment by xet7** [comment]
@mrtndwrd 

Pull requests welcome. I don't know how it works.

**Comment by mrtndwrd** [comment]
Alright, I made a PR to at least host the newest 1.1.1 chart on the chart repository. I think it might have disappeared because of a merge conflict.
